### PR TITLE
Svg css

### PR DESCRIPTION
**Pull request by uber5001**
The purpose of this was to move styling out of dot.js and into CSS. I ended up adding a CSS generator to create CSS rules based on our globals/config. At 95 additions and 11 deletions... is this worth it?

Please review. I wrote this late at night and don't want to merge crap code.

### CODE REVIEW

**Comment by Awk34** [comment]
pls remove classname data element :]

**Comment by uber5001** [comment]
This doesn't make sense to do. The `name`, `className`, and `shortName` all serve different purposes.
- `name` - This is the name of the node itself, and is the next best thing to a description. It is meant to be displayed as a label for this node (perhaps in menus).
- `shortName` - This is meant to be a shorter version of the `name`, to be used in areas where the normal `name` will not fit. Additionally, we are using it for the default display names of nodes.
- `className` - This is meant to be used only as a `className`. It is a value that the user will never see, but the value is restricted by the naming conventions of classes. **This means that the `className` cannot contain spaces, but`name` and `shortName` can.**

I don't think it makes sense to combine className and name, or className and shortName. After trying it out, an error was thrown when trying to use "Low Frequency Oscillator" as a class name.

**Comment by Awk34** [comment]
I _was_ thinking about the whole spaces thing. If we never used spaces with `name` then it would be okay to lowercase it. But like you said, there could be instances where we would have names with spaces, so you are correct.

**Comment by uber5001** [comment]
Yes, but if we have a side-menu for the new node menu, we would still need another field in order to display the type of node. That menu/field should say "Oscillator", "Dynamics Compressor", "Gain", "Output", etc., not "Osc", "Comp", "Gain", "Out", etc. (though maybe a short name menu could be an option).

I don't think we ever want the user to see "DynamicsCompressor", or "LowFrequencyOscillator".

**Comment by Awk34** [comment]
Exactly.

**Pull request merged**
